package org.etsi.uri.ts102204.etsi204_kiuru_wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2015-02-10T10:55:20.814+01:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "MSS_SignatureService", 
                  wsdlLocation = "file:./mobileid.wsdl",
                  targetNamespace = "http://uri.etsi.org/TS102204/etsi204-kiuru.wsdl") 
public class MSSSignatureService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://uri.etsi.org/TS102204/etsi204-kiuru.wsdl", "MSS_SignatureService");
    public final static QName MSSSignaturePort = new QName("http://uri.etsi.org/TS102204/etsi204-kiuru.wsdl", "MSS_SignaturePort");
    static {
        URL url = null;
        try {
            url = new URL("file:./mobileid.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MSSSignatureService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:./mobileid.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MSSSignatureService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MSSSignatureService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MSSSignatureService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MSSSignatureService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MSSSignatureService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MSSSignatureService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns MSSSignatureType
     */
    @WebEndpoint(name = "MSS_SignaturePort")
    public MSSSignatureType getMSSSignaturePort() {
        return super.getPort(MSSSignaturePort, MSSSignatureType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MSSSignatureType
     */
    @WebEndpoint(name = "MSS_SignaturePort")
    public MSSSignatureType getMSSSignaturePort(WebServiceFeature... features) {
        return super.getPort(MSSSignaturePort, MSSSignatureType.class, features);
    }

}
